### ISSUE TITLE
[x] button showing up at wrong offset

### ISSUE THREAD

**Issue by darianhickman** [darian311/VillageMakeover#10]
![screen shot 2015-03-20 at 12 36 15 pm](https://cloud.githubusercontent.com/assets/1481299/6756084/ee2ef54e-cefd-11e4-8a56-5f94999e21d7.png)
You can recreate issue at http://villagegamedev2.appspot.com/

**Comment by umutnacak** [comment]
I have hidden close button for this dialog in one of latest commits since it's auto closing itself.

**Comment by umutnacak** [comment]
In this commit to be exact: f1ff70af3ae48ecfbd62ca534f796996056b8c10
client/gameClasses/ui/BuyStatus.js -> this.closeButton.hide();

**Comment by umutnacak** [comment]
http://villagegamedev2.appspot.com/ is not up to date.

**Comment by darianhickman** [comment]
Can we update the behavror to get to the top right like expected.  Eventually we want payment workflow to behave like most farm games on Facebook.

**Comment by umutnacak** [comment]
Sure
