### ISSUE TITLE
Scroll zoom doesn't work in Safari 

### ISSUE THREAD

**Issue by darianhickman** [darian311/VillageMakeover#13]
![screen shot 2015-03-23 at 3 10 55 pm](https://cloud.githubusercontent.com/assets/1481299/6788305/de8d36c8-d16e-11e4-9b52-a502ff3d9c5b.png)
This is the screen which is unresponsive when I attempt to use scrollwheel.

**Comment by umutnacak** [comment]
Can you delete your history and website data. Because there is no login id either. Maybe your browser is using an old game.js? I can use both mouse wheel and touchpad with two finger scroll on Mac and Safari.
