### ISSUE TITLE
Coin dropping animation never stops

### ISSUE THREAD

**Issue by darianhickman** [darian311/VillageMakeover#14]
Here's a sample of console about same time as error.  Not sure if repeatable: 
game.js:1 IGE _log_ [$i_114:ige] : Texture image (./assets/textures/sprites/wallSE.png) loaded successfully
game.js:1 IGE _log_ [$i_114:ige] : Texture image (./assets/textures/sprites/flowerPot1.png) loaded successfully
game.js:1 IGE _log_ [$i_114:ige] : Texture image (assets/textures/sprites/generator.png) loaded successfully
game.js:1 Stack:     at e.i [as log](http://game.villagethegame.com/client/deploy/game.js:1:10604)
 ----     at e.$i_54.extend._applyCells (http://game.villagethegame.com/client/deploy/game.js:4:11585)
 ----     at e.$i_54.extend._textureLoaded (http://game.villagethegame.com/client/deploy/game.js:4:10960)
 ----     at HTMLImageElement.ige.isClient.ige._textureImageStore.(anonymous function).e.onload (http://game.villagethegame.com/client/deploy/game.js:4:1149)
game.js:1 IGE _warning_ [$i_55] : Cell width is a floating-point number! (Image Width 1055 / Number of Columns 3 = 351.6666666666667) in file: assets/textures/sprites/generator.png
game.js:1 IGE _log_ [$i_114:ige] : Texture image (./assets/textures/sprites/clothingLine.png) loaded successfully
game.js:1 IGE _log_ [$i_114:ige] : Texture image (./assets/textures/greendot.png) loaded successfully
game.js:1 IGE _log_ [$i_114:ige] : Texture image (./assets/textures/reddot.png) loaded successfully
game.js:1 IGE _log_ [$i_114:ige] : All textures have loaded
game.js:1 IGE _log_ [$i_14] : Setting up input event listeners...
game.js:1 IGE _log_ [$i_114:ige] : Starting engine...
game.js:1 IGE _log_ [$i_114:ige] : Engine started

**Comment by umutnacak** [comment]
I see the same bug now. I think game doesn't like zero coins. Did you change catalog making some items to have zero coin price?

**Comment by darianhickman** [comment]
Yep, i want the game design be either/or  coins vs cash.  Are you work on
any fixes listed in Asana project?  Put a heart on the one you're tackling.

Really glad to see these things moving forward.

On Wed, Mar 25, 2015 at 11:55 AM, umutnacak notifications@github.com
wrote:

> I see the same bug now. I think game doesn't like zero coins. Did you
> change catalog making some items to have zero coin price?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darian311/VillageMakeover/issues/14#issuecomment-86093890
> .

## 

Darian Hickman |  (310) 439-8573  | http://www.linkedin.com/in/darianhickman

**Comment by umutnacak** [comment]
Yes I am working on a couple of tasks now.

**Comment by umutnacak** [comment]
Can you check http://umutvillage.appspot.com/client/ I have updated a couple of things.

**Comment by darianhickman** [comment]
Looks good!  I see you removed the energy, xp already. Looks like zoom in safari is working too.

**Comment by darianhickman** [comment]
So the coin animation no longer goes on forever.  Now it just goes on too long.  Can you trim it to 2 seconds?

**Comment by umutnacak** [comment]
I guess it calculates using number of coins. Do you want it to last always
2 seconds?

**Comment by darianhickman** [comment]
Yeah two secs tops.  if we changed coin tween based on quantity it would be at most 3 levels of coin tween.
