### ISSUE TITLE
What is                 var hientity = new HiEntity()

### ISSUE THREAD

**Issue by darianhickman** [darian311/VillageMakeover#26]
Please add a little documentation in client.js.  I'm trying to troubleshoot redded out areas

**Comment by umutnacak** [comment]
I'm trying to understand as well. I have a very small progress, I hope I can get it working in a couple of hours. This part is really complicated.

**Comment by umutnacak** [comment]
I have found the bugs, now fixing. Wow what a journey.

**Comment by darianhickman** [comment]
Lol thanks was it our code or the game engine code?

**Comment by umutnacak** [comment]
Game code(not engine), but just a couple of tweaks actually. 3 instead of 1, undefined variables etc. But I tried lots of things to find those.

**Comment by umutnacak** [comment]
Can I change some properties on catalog sheet? I guess I have appropriate authorization.

**Comment by darianhickman** [comment]
Yes. go for it.

On Thu, Mar 26, 2015 at 1:15 PM, umutnacak notifications@github.com wrote:

> Can I change some properties on catalog sheet? I guess I have appropriate
> authorization.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darian311/VillageMakeover/issues/26#issuecomment-86629626
> .

## 

Darian Hickman |  (310) 439-8573  | http://www.linkedin.com/in/darianhickman

**Comment by umutnacak** [comment]
Ok I'm going to play with anchor positions a little bit. After that I will make a commit and deploy to umutvillage.

**Comment by umutnacak** [comment]
Hmm google sheet says 'View only'. Do I need additional permission?

**Comment by darianhickman** [comment]
reload and see if it works now.

On Thu, Mar 26, 2015 at 1:32 PM, umutnacak notifications@github.com wrote:

> Hmm google sheet says 'View only'. Do I need additional permission?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darian311/VillageMakeover/issues/26#issuecomment-86635731
> .

## 

Darian Hickman |  (310) 439-8573  | http://www.linkedin.com/in/darianhickman

**Comment by umutnacak** [comment]
Thanks. If I don't get the result I want I will undo changes.

**Comment by umutnacak** [comment]
Nope anchor is not the one I am looking for. I won't make any changes for now.

**Comment by umutnacak** [comment]
You can view the latest version on http://umutvillage.appspot.com/client/
Not perfect but at least no bugs(I hope)

**Comment by darianhickman** [comment]
cool.  coins behaving better and almost in right spot. :)

On Thu, Mar 26, 2015 at 3:36 PM, umutnacak notifications@github.com wrote:

> You can view the latest version on http://umutvillage.appspot.com/client/
> Not perfect but at least no bugs(I hope)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darian311/VillageMakeover/issues/26#issuecomment-86685428
> .

## 

Darian Hickman |  (310) 439-8573  | http://www.linkedin.com/in/darianhickman

**Comment by umutnacak** [comment]
isuue #24 #25 #26 is resolved in the latest pull request, and all of my Asana tasks have been completed.
