### ISSUE TITLE
What do i need to update to make drilling_truck.png show up correctly? 

### ISSUE THREAD

**Issue by darianhickman** [darian311/VillageMakeover#28]
![screen shot 2015-03-26 at 3 42 35 pm](https://cloud.githubusercontent.com/assets/1481299/6855455/d57a045a-d3ce-11e4-945e-cdd387ac6df3.png)

**Comment by umutnacak** [comment]
Adjust bounds3d, but I don't know how you calculate the correct dimensions.

**Comment by umutnacak** [comment]
By the way cell should be 1

**Comment by umutnacak** [comment]
It looks good now, but bounds3d is a little big I think.

**Comment by darianhickman** [comment]
ok can you add notes in row 2 of each column to tell what each column
controls.
https://docs.google.com/a/villagethegame.com/spreadsheets/d/1imTZeg1aM4d2cWXpPPfHbTpQP6KX2HyxydqJfcejHtY/edit#gid=0

On Thu, Mar 26, 2015 at 4:08 PM, umutnacak notifications@github.com wrote:

> It looks good now, but bounds3d is a little big I think.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darian311/VillageMakeover/issues/28#issuecomment-86695015
> .

## 

Darian Hickman |  (310) 439-8573  | http://www.linkedin.com/in/darianhickman

**Comment by umutnacak** [comment]
Sure, just correct grammatical errors.
