### ISSUE TITLE
Buildable hilite needs to show when changing location of building.

### ISSUE THREAD

**Issue by darianhickman** [darian311/VillageMakeover#35]
I can move buildings around like expected.

**Comment by umutnacak** [comment]
hiEntity(red dots) shows now. I have moved HiEntity class to a new file, hiEntity to GraphLevel1 and fixed a couple of bugs related to moveObjects. Demo: http://umutvillage.appspot.com/client/ (clear browser cache before visit). And code: https://github.com/umutnacak/VillageMakeover/commits/hientityrefactor (last 3 commits).
If you are happy with the changes, I can create a pull request.
Ps: I couldn't get village2013 up and running so I have worked on village makeover.

**Comment by darianhickman** [comment]
Ok if you want to see village2013 it's at villagethegame 311.appspot.com

**Comment by umutnacak** [comment]
We have switched to drawGrid and disabled hiEntity
