### ISSUE TITLE
Need proper handling of 0 coins.

### ISSUE THREAD

**Issue by darianhickman** [darian311/VillageMakeover#4]
Javascript errors occur when trying to build an object without the required resources.  For example, trying to build Hut 1 without any money, or Hut 2 with less than 10 coins.  When this is attempted, nothing happens and the game freezes for a little bit.  No in game error given.  Javascript errors shown below.
https://mail.google.com/mail/u/0/?ui=2&ik=dcc9604119&view=fimg&th=14c0ac8da6c5c2b2&attid=0.2&disp=emb&realattid=ii_14c0ab7ae4aa7174&attbid=ANGjdJ-AXtM-WREzCqx-eO_q022WTH7slJzh_em3lI1x2SoY9pyRstmBogkwovKhY-B5Kf6wqNCiebWkYjly_jpblu0EBTzojfk8yCnbRqknXGk0nyDcZSMr0-rwz0o&sz=s0-l75-ft&ats=1426524247094&rm=14c0ac8da6c5c2b2&zw&atsh=1

**Comment by umutnacak** [comment]
There is a pull request targeting this issue.

**Comment by darianhickman** [comment]
I saw the error is eliminated. Yay! How are things going with integrating the new Coins dialog I sent.  Hopefully the logic is parallel and simpler than the Cash Dialog.

**Comment by umutnacak** [comment]
Well, now I am making the Coins dialog, and I need to ask you something. If
the player doesn't have enough village bucks then what happens? I decided
to show cash dialog, but maybe you want something different. I will make
some commits after dinner. You can revise the code and make suggestions.

**Comment by darianhickman** [comment]
Perfect! That's exactly what should happen. I'll double check FarmVille to
see what kind of messages it needs though

**Comment by umutnacak** [comment]
Please review the code in pull request. I am going to make a deploy to
umutvillage in a couple of minutes.

**Comment by darianhickman** [comment]
Can you change assets to coins?  Looks good!

**Comment by darianhickman** [comment]
Let's change starting coins to 1000 at least or higher if it's lower than that now.

**Comment by umutnacak** [comment]
Ok

**Comment by umutnacak** [comment]
I'm closing a couple of issues. You can reopen them if you are not satisfied.
