### ISSUE TITLE
gspread authentication issue

### ISSUE THREAD

**Issue by umutnacak** [darian311/VillageMakeover#46]
This is the reason: Email & password authentication was deprecated by Google on April 20th. You need to use oAuth2 to access your spreadsheets.

**Comment by darianhickman** [comment]
Do you know how to update to oauth2?

**Comment by umutnacak** [comment]
I'm reading the docs.

**Comment by darianhickman** [comment]
Thanks

**Comment by umutnacak** [comment]
Could you check umutvillage build dialog please? Catalog should be fixed
now.

**Comment by umutnacak** [comment]
News feed is ok too. Did you do/accept anything?

**Comment by umutnacak** [comment]
Oh my god, I'm only testing on localhost haven't uploaded to umutvillage
yet. Sorry.

**Comment by umutnacak** [comment]
Ok check now please.
