### ISSUE TITLE
Safari error

### ISSUE THREAD

**Issue by umutnacak** [darian311/VillageMakeover#7]
I am getting this error in Safari:
ReferenceError: Can't find variable: TouchEvent

Mac OS X 10.10.2
Safari 8.0.4

**Comment by darianhickman** [comment]
Is this blocking game play?

**Comment by umutnacak** [comment]
Yes. I will investigate more today.

**Comment by umutnacak** [comment]
Ok, so this is because of fool moron's pinchzoomcomponent. According to this document: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Touch_events TouchEvent is only supported in Chrome for Desktop. Adding the following condition to mouse events seems like fixes the issue:
typeof TouchEvent !== 'undefined'
I didn't make a thorough test but let's say this is the issue, should I alter PinchZoomComponent.js?

**Comment by darianhickman** [comment]
What are the chances it will break the scroll to zoom?

On Thu, Mar 19, 2015 at 8:35 AM, umutnacak notifications@github.com wrote:

> Ok, so this is because of fool moron's pinchzoomcomponent. According to
> this document:
> https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Touch_events
> TouchEvent is only supported in Chrome for Desktop. Adding the following
> condition to mouse events seems like fixes the issue:
> typeof TouchEvent !== 'undefined'
> I didn't make a thorough test but let's say this is the issue, should I
> alter PinchZoomComponent.js?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darian311/VillageMakeover/issues/7#issuecomment-83538109
> .

## 

Darian Hickman |  (310) 439-8573  | http://www.linkedin.com/in/darianhickman

**Comment by umutnacak** [comment]
I don't think it will break anything. Did you download the component from a
github repo? Maybe we should tell the developer to fix this issue.
Otherwise we need to fix this, because the game is unplayable in browsers
other than Chrome. Did you test in other browsers?

**Comment by darianhickman** [comment]
I think he's responsive so let him fix first

**Comment by darianhickman** [comment]
Can we remove pinch zoom altogether ? I want to focus on polished desktop experience and ignore mobile til better funding comes through

**Comment by umutnacak** [comment]
It's your call :) I'm going to disable it in the next commit. You can enable it whenever you want.

**Comment by darianhickman** [comment]
As long experience on desktop is good we can keep going forward

**Comment by umutnacak** [comment]
Pinch zoom component is disabled in this commit: 02ee50d6528349e684546804669558f455d53e00
I'm closing this issue for now, you can address this at a later time.
