### ISSUE TITLE
Errors still when hitting 0 coins

### ISSUE THREAD

**Issue by darianhickman** [darian311/VillageMakeover#9]
I attempted to buy a hut that would put me negative.  Nothing happened visually and these errors happend:
reduce assets Object
game.js:9 Uncaught TypeError: Cannot read property 'show' of undefined
88game.js:9 Uncaught TypeError: Cannot read property 'coins' of null
149game.js:9 Uncaught TypeError: Cannot read property 'opacity' of null
![screen shot 2015-03-20 at 11 38 33 am](https://cloud.githubusercontent.com/assets/1481299/6754887/d4df2d32-cef5-11e4-8be9-6a91be4c5554.png)

**Comment by umutnacak** [comment]
http://villagegamedev2.appspot.com/ is not up to date.

**Comment by darianhickman** [comment]
Good behavior now. But we'll make even better with message.
